# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
image: registry.cn-hangzhou.aliyuncs.com/ksco/ksco:version1

before_script:
  - git clone -b develop-post http://ci:${CI_JOB_TOKEN}@192.168.20.201/filecoin-project/lotus.git
  - git clone -b proofs-v5.4.0 http://ci:${CI_JOB_TOKEN}@192.168.20.201/firefly-rust/fil-proofs.git
  - git clone -b dev http://ci:${CI_JOB_TOKEN}@192.168.20.201/filecoin-project/go-fil-markets.git
  - git clone -b dev http://ci:${CI_JOB_TOKEN}@192.168.20.201/filecoin-project/specs-storage.git
  - source /etc/profile
after_script:
  - echo "After script section"

build1:
  stage: build
  script:
    - echo "build start"
    - go mod tidy -v
    - git --no-pager diff go.mod go.sum
    - git --no-pager diff --quiet go.mod go.sum
    - golangci-lint run -v --timeout 2m --concurrency 16
    - ! go fmt ./... 2>&1 | read
    - make debug
    - apt install ocl-icd-opencl-dev libhwloc-dev
    - git submodule sync
    - git submodule update --init
    - cd extern/oni && git submodule sync
    - cd ../..
    - cd extern/oni && git submodule update --init
    - cd ../..
    - cd extern/filecoin-ffi && make
    - cd ../..
    - cd extern/oni/lotus-soup && go mod edit -replace github.com/filecoin-project/lotus=../../../ && go mod edit -replace github.com/filecoin-project/filecoin-ffi=../../filecoin-ffi && go mod edit -replace github.com/supranational/blst=../../blst
    - cd ../../..
    - pushd extern/oni/lotus-soup && go build -tags=testground .
    - cd ../../..
    - make deps
    - make deps lotus
    - go generate ./...
    - git --no-pager diff
    - git --no-pager diff --quiet
    - echo "build end"

test_window_post:
  stage: test
  script:
    - gotestsum \
      --format pkgname-and-test-fails \
      -- \
      -coverprofile=coverage.txt -coverpkg=github.com/filecoin-project/lotus/... \
      -run=TestWindowedPost \
      ./...
test_storage:
  stage: test
  script:
    - gotestsum \
      --format pkgname-and-test-fails \
      -- \
      -coverprofile=coverage.txt -coverpkg=github.com/filecoin-project/lotus/... \
      -timeout 30m \
      ./storage/... ./extern/...

test_short:
  stage: test
  script:
    - gotestsum \
      --format pkgname-and-test-fails \
      -- \
      -coverprofile=coverage.txt -coverpkg=github.com/filecoin-project/lotus/... \
      --timeout 10m --short \
      ./...

test_node:
  stage: test
  script:
    - gotestsum \
      --format pkgname-and-test-fails \
      -- \
      -coverprofile=coverage.txt -coverpkg=github.com/filecoin-project/lotus/... \
      -timeout 30m \
      ./node/...

test_conformance_bleeding_edge:
  stage: test
  script:
    - gotestsum \
      -- \
      -v -coverpkg ./chain/vm/,github.com/filecoin-project/specs-actors/... -coverprofile=/tmp/conformance.out ./conformance/

test_conformance:
  stage: test
  script:
    - gotestsum \
      -- \
      -v -coverpkg ./chain/vm/,github.com/filecoin-project/specs-actors/... -coverprofile=/tmp/conformance.out ./conformance/

test_cli:
  stage: test
  script:
    - gotestsum \
      --format pkgname-and-test-fails \
      -- \
      -coverprofile=coverage.txt -coverpkg=github.com/filecoin-project/lotus/... \
      -timeout 30m \
      ./cli/... ./cmd/... ./api/...

test_chain:
  stage: test
  script:
    - gotestsum \
      --format pkgname-and-test-fails \
      -- \
      -coverprofile=coverage.txt -coverpkg=github.com/filecoin-project/lotus/... \
      -timeout 30m \
      ./chain/...

test:
  stage: test
  script:
    - gotestsum \
      --format pkgname-and-test-fails \
      -- \
      -coverprofile=coverage.txt -coverpkg=github.com/filecoin-project/lotus/... \
      -timeout 30m \
      ./...

go_test:
  stage: test
  script:
    - go test ./...

deploy1:
  stage: deploy
  script:
    - echo "Do your deploy here"
