# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
image: circleci/golang:1.15.5

.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
    GOPROXY: https://goproxy.cn,direct
  before_script:
    - mkdir -p .go
  cache:
    paths:
      - .go/pkg/mod/

before_script:
  - cd ..
  - rm -rf lotus-post fil-proofs go-fil-markets specs-storage
  - git clone -b develop-post http://ci:${CI_JOB_TOKEN}@192.168.20.201/filecoin-project/lotus.git lotus-post
  - git clone -b proofs-v5.4.0 http://ci:${CI_JOB_TOKEN}@192.168.20.201/firefly-rust/fil-proofs.git
  - git clone -b dev http://ci:${CI_JOB_TOKEN}@192.168.20.201/filecoin-project/go-fil-markets.git
  - git clone -b dev http://ci:${CI_JOB_TOKEN}@192.168.20.201/filecoin-project/specs-storage.git
  - cd lotus-post
  - sed -i 's|deb.debian.org|mirrors.ustc.edu.cn|g' /etc/apt/sources.list
  - sed -i 's|security.debian.org/debian-security|mirrors.ustc.edu.cn/debian-security|g' /etc/apt/sources.list
  - apt install -y ocl-icd-opencl-dev libhwloc-dev
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.33.0
  - go get gotest.tools/gotestsum

after_script:
  - echo "After script section"

build_develop:
  stage: build
  extends: .go-cache
  script:
    - make clean
    - git submodule update --init --recursive
    # - golangci-lint run -v --timeout 2m --concurrency 16
    - go mod tidy -v
    - go fmt ./...
    - make deps
    #  lotus-miner-sched lotus-amd-worker lotus-gpu-worker
    - make lotus-miner lotus-worker

build_develop-post:
  stage: build
  extends: .go-cache
  script:
    - cd ../lotus-post || exit
    - make clean
    - git submodule sync
    - git submodule update --init
    - source /etc/profile
    - golangci-lint run -v --timeout 2m --concurrency 16
    - go mod tidy -v
    - go fmt ./...
    - make deps
    - make lotus-miner lotus-worker lotus-shed  lotus

test_window_post:
  stage: test
  extends: .go-cache
  script:
    - gotestsum \
      --format pkgname-and-test-fails \
      -- \
      -coverprofile=coverage.txt -coverpkg=github.com/filecoin-project/lotus/... \
      -run=TestWindowedPost \
      ./...

test_storage:
  stage: test
  extends: .go-cache
  script:
    - gotestsum \
      --format pkgname-and-test-fails \
      -- \
      -coverprofile=coverage.txt -coverpkg=github.com/filecoin-project/lotus/... \
      -timeout 30m \
      ./storage/... ./extern/...

test_short:
  stage: test
  extends: .go-cache
  script:
    - gotestsum \
      --format pkgname-and-test-fails \
      -- \
      -coverprofile=coverage.txt -coverpkg=github.com/filecoin-project/lotus/... \
      --timeout 10m --short \
      ./...

test_node:
  stage: test
  extends: .go-cache
  script:
    - gotestsum \
      --format pkgname-and-test-fails \
      -- \
      -coverprofile=coverage.txt -coverpkg=github.com/filecoin-project/lotus/... \
      -timeout 30m \
      ./node/...

test_conformance_bleeding_edge:
  stage: test
  extends: .go-cache
  script:
    - gotestsum \
      -- \
      -v -coverpkg ./chain/vm/,github.com/filecoin-project/specs-actors/... -coverprofile=/tmp/conformance.out ./conformance/

test_conformance:
  stage: test
  extends: .go-cache
  script:
    - gotestsum \
      -- \
      -v -coverpkg ./chain/vm/,github.com/filecoin-project/specs-actors/... -coverprofile=/tmp/conformance.out ./conformance/

test_cli:
  stage: test
  extends: .go-cache
  script:
    - gotestsum \
      --format pkgname-and-test-fails \
      -- \
      -coverprofile=coverage.txt -coverpkg=github.com/filecoin-project/lotus/... \
      -timeout 30m \
      ./cli/... ./cmd/... ./api/...

test_chain:
  stage: test
  extends: .go-cache
  script:
    - gotestsum \
      --format pkgname-and-test-fails \
      -- \
      -coverprofile=coverage.txt -coverpkg=github.com/filecoin-project/lotus/... \
      -timeout 30m \
      ./chain/...

test:
  stage: test
  extends: .go-cache
  script:
    - gotestsum \
      --format pkgname-and-test-fails \
      -- \
      -coverprofile=coverage.txt -coverpkg=github.com/filecoin-project/lotus/... \
      -timeout 30m \
      ./...

go_test:
  stage: test
  extends: .go-cache
  script:
    - go test ./...

deploy1:
  stage: deploy
  extends: .go-cache
  script:
    - echo "Do your deploy here"
